---
# This is a sample database file for the DataMapper ORM
development: &defaults
  # These are the settings for repository :default
  adapter:  jdbchsqldb
  database: ../../scripting/rails/db/limewire_development.db
  username: sa
  password:
 
  # Add more repositories
  # repositories:
  #   repo1:
  #     adapter:  sqlite3
  #     database: sample_1_development.db
  #   repo2:
  #     ...
 
test:
  <<:       *defaults
  database: db/limewire_test.db
 
  # repositories:
  #   repo1:
  #     database: sample_1_test.db
 
production:
  <<:       *defaults
  database: db/limewire_production.db
 
  # repositories:
  #   repo1:
  #     database: sample_production.db
 
rake:
  <<: *defaults
